services:
  postgres:
    image: postgres:18
    container_name: openlibrarydb
    environment:
      POSTGRES_DB: open_library
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:7
    container_name: openlibraryredis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
